### ISSUE TITLE
小白不懂，请问这个怎么用？

### ISSUE THREAD

**Issue by wlhwlh0482** [bclswl0827/bond-bot#1]

**Comment by bclswl0827** [comment]
1. 在 [release](https://github.com/bclswl0827/bond-bot/tree/master/release) 下载对应架构的预编译好的可执行文件
2. 申请 Telegram Bot，取得 Token，填入 config.json
3. 创建群组或频道，将机器人拉进去，设为管理员
4. 取得群组或频道 ID，填入 config.json
5. 在 config.json 设定推送时刻，运行程序即可
